### ISSUE TITLE
Add GIF of git init command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#1]
`git init --q`
`git init --template`
`git init --separate-git-dir<git dir>`
`git --shared[=(false|true|umask|group|all|world|everybody|0xxx)]`
`git init unmask`

**Comment by learnerAbhishek** [comment]
I want to contribute to your GitGIFs project. I just have some queries (**read dumb questions**).

1 Shall I place the GIFs in the gitgifs/static/gifs/ Folder and make the pull requests.

2 Do we need to install everything that is mentioned in **requirements.txt** .

**Comment by tapaswenipathak** [comment]
I'm adding a sample.

**Comment by learnerAbhishek** [comment]
@tapaswenipathak I want to work on this issue. Please assign it to me.

**Comment by sakshivij** [comment]
@tapaswenipathak work by ticket means, adding images here too?

**Comment by sakshivij** [comment]
@tapaswenipathak do i submit multiple pull request for every ticket?

**Comment by tapaswenipathak** [comment]
No, per ticket one pull request.
