### ISSUE TITLE
Add GIF of git stash command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#31]
- [x] `git stash list <options>`
- [x] `git stash show <stash>`
- [x] `git stash drop --quiet <stash>`
- [x] `git stash branch <branchname> <stash>`
- [x] `git stash clear`
- [ ] `git stash create <message>`
- [ ] `git stash store -m|--message <message>`

**Comment by sakshivij** [comment]
@tapaswenipathak  should I attach GIF here or separately as a folder in repository?

**Comment by tapaswenipathak** [comment]
On Wed, May 22, 2019 at 9:52 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak should I attach GIF here or separately as a folder in repository?

The GIF should be added in
https://github.com/tapaswenipathak/GitGIFs/tree/master/gitgifs/static/gifs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
