### ISSUE TITLE
Add GIFs of git cat-file command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#36]
- [x] `git cat-file -t -s`
- [ ] `git cat-file --batch`

**Comment by sakshivij** [comment]
cc @tapaswenipathak  
Will need help with second part

**Comment by tapaswenipathak** [comment]
On Mon, Jun 24, 2019 at 1:36 AM SAKSHI VIJ <notifications@github.com> wrote:
>
> cc @tapaswenipathak
> Will need help with git cat-file --batch command

can you write in the ticket and post, i will ticket till morning
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
