### ISSUE TITLE
Add GIFs of git bissect command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#38]
- [x] `git bisect reset [<commit>]`
- [x] `git bisect log`
- [x] `git bisect help`
- [ ] `git bisect run <cmd>`
- [x] `git bisect skip [(<rev>)]`
- [x] `git bisect bad`
- [x] `git bisect good tag`

**Comment by sakshivij** [comment]
cc @tapaswenipathak will need help run part
