### ISSUE TITLE
GIFs should have

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#59]
@sakshivij 

- Only `$` Prompt
- White screen, black text
- Run git command
- Run list command for the git command
- Based on the os you have, I will let you know the screen dimensions.

**Comment by sakshivij** [comment]
@tapaswenipathak thanks. These help. I will make changes accordingly.

**Comment by tapaswenipathak** [comment]
Name the gifs as `git-command-name-option-name`.
