### ISSUE TITLE
Add GIFs of git clean command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#6]
- [x] `git clean -d`
- [x] `git clean --force`
- [x] `git clean --interactive`
- [x] `git clean quiet`
- [x] `git clean --dry-run`
- [x] `git clean --exclude=<pattern>`
- [x] `git clean -x`

**Comment by sakshivij** [comment]
>     * `git clean -d`
> 
>     * `git clean --force`
> 
>     * `git clean --interactive`
> 
>     * `git clean quiet`
> 
>     * `git clean --dry-run`
> 
>     * `git clean --exclude=<pattern>`
> 
>     * `git clean -x`

Any inputs on 
1. exclude-pattern
2. git clean -x?
3. git clean q
?

**Comment by tapaswenipathak** [comment]
On Sat, 1 Jun 2019, 07:45 SAKSHI VIJ <notifications@github.com wrote:

> * `git clean -d`
>
> * `git clean --force`
>
> * `git clean --interactive`
>
> * `git clean quiet`
>
> * `git clean --dry-run`
>
> * `git clean --exclude=<pattern>`
>
> * `git clean -x`
>
> Any inputs on git clean -x?
>

Just run these commands. Ping me on Slack if there is anything.
