### ISSUE TITLE
GIFs creation

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#68]
@sakshivij Submit these gifs by eod. Let me know if you need more inputs.

![9FEC84E0-9515-48B0-BF75-3100CCD0FB60](https://user-images.githubusercontent.com/4143778/58686388-51adeb00-839c-11e9-9648-80528ce980f1.png)

**Comment by sakshivij** [comment]
@tapaswenipathak can you please submit the images in parts? Some parts are not clearly visible.

**Comment by tapaswenipathak** [comment]
On Fri, May 31, 2019 at 10:05 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak can you please submit the images in parts?

Sure.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
![git init](https://user-images.githubusercontent.com/4143778/58721326-51d8d580-83f2-11e9-8bda-63d14c92209c.png)

**Comment by tapaswenipathak** [comment]
![git clone commands](https://user-images.githubusercontent.com/4143778/58721618-01ae4300-83f3-11e9-8c9d-c6d0fca6695a.png)

**Comment by tapaswenipathak** [comment]
![git help](https://user-images.githubusercontent.com/4143778/58721687-2c989700-83f3-11e9-8079-1396487111b3.png)

**Comment by tapaswenipathak** [comment]
![git diff](https://user-images.githubusercontent.com/4143778/58722002-f27bc500-83f3-11e9-8caa-3687dafc4ca6.png)

**Comment by tapaswenipathak** [comment]
![git commands](https://user-images.githubusercontent.com/4143778/58722463-18ee3000-83f5-11e9-977d-6074a14b2937.png)

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing.

**Comment by sakshivij** [comment]
That's fine. Just that init --q doesn't seem to work according to instructions listed above

**Comment by tapaswenipathak** [comment]
On Fri, May 31, 2019 at 11:16 PM SAKSHI VIJ <notifications@github.com> wrote:
>
>  init --q doesn't work as per instructions listed above

Slack chat?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
ok

**Comment by tapaswenipathak** [comment]
ping
