### ISSUE TITLE
Add GIFs of git rm command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#7]
- `git rm -f`
- `git rm --cached`
- `git rm --quiet`

**Comment by sakshivij** [comment]
@tapaswenipathak  Assigning ticket to you. Created PR

**Comment by tapaswenipathak** [comment]
On Sat, Jun 1, 2019 at 6:49 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak Assigning ticket. Created PR

After you are done, just assign pr on my name.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
Tapasweni
