### ISSUE TITLE
Add GIFs of git mv command

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/GitGIFs#8]
- `git mv -f`
- `git rm -k`
- `git rm --dry-run`
- `git rm --verbose`

**Comment by sakshivij** [comment]
Getting errors for these commands. Working on finding issue.

**Comment by sakshivij** [comment]
~/new_repository$ git mv --force file1.txt dir1/
fatal: not under version control, source=file1.txt, destination=dir1/file1.txt
 
Any ideas why this works sometimes, and other time I get this error.

**Comment by tapaswenipathak** [comment]
On Thu, Jun 6, 2019 at 11:26 AM SAKSHI VIJ <notifications@github.com> wrote:
>
> ~/new_repository$ git mv --force file1.txt dir1/
> fatal: under version control, source=file1.txt, destination=dir1/file1.txt
>
> Any ideas why this works sometimes?

I didn't get you?! let's chat in Slack.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
Getting an error :
fatal: not under version control, source=file.txt, destination=fol/file.txt

For every command. Any suggestions @tapaswenipathak

**Comment by sakshivij** [comment]
cc @tapaswenipathak 
Suggest changes
