### ISSUE TITLE
Ticket help

### ISSUE THREAD

**Issue by sakshivij** [tapaswenipathak/GitGIFs#93]
**Need help in diagram for following:**
git remote - #17
git fetch - #18
git archive - #19
git tag - #22
git describe - #24
git rebase #29
git revert #30
git clone #2
git grep #34

**Facing error for following**
git clone #2
git help #3
git clean #6
git mv  #8
git checkout #15
git log #25
git stash #31
git credential #26
git mergetool #28

**Comment by sakshivij** [comment]
cc @tapaswenipathak

**Comment by tapaswenipathak** [comment]
git cat-file --batch from https://github.com/tapaswenipathak/GitGIFs/issues/36

**Comment by tapaswenipathak** [comment]
git bisect run <cmd> from https://github.com/tapaswenipathak/GitGIFs/issues/38

**Comment by sakshivij** [comment]
I'll update this for further by removing or adding appropriate commands.

**Comment by sakshivij** [comment]
git checkout --quiet from #15
